## Usage of zip function

In [1]:
L1 = [1,2,3]
L2 = [2,4,6]
result = 0
for item in zip(L1 , L2):
    #dot product
    result += item[0] * item[1]
result

28

# Numpy

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
kanto = np.array([73 , 67 , 43])

In [5]:
kanto

array([73, 67, 43])

In [6]:
w1 , w2 , w3 = 0.8 , 0.4 , 0.3

In [7]:
weights = np.array([w1 , w2 , w3])

In [8]:
weights

array([0.8, 0.4, 0.3])

In [9]:
kanto[0]

73

In [10]:
weights[2]

0.3

## Operations on Numpy Arrays

In [11]:
kanto * weights

array([58.4, 26.8, 12.9])

In [12]:
(kanto * weights).sum()

98.10000000000001

In [13]:
np.dot(kanto , weights)

98.10000000000001

#### Reasons to Use

##### Ease of Use: Write small and intutive codes which is not possible in python
##### Performance: Numpy operations and functions are implemented in C++

In [14]:
climate_data = np.array([
    [73 , 67 , 43] ,
    [73 , 67 , 43] ,
    [73 , 67 , 43] ,
    [73 , 67 , 43] ,
    [73 , 67 , 43]
])

In [15]:
climate_data.shape

(5, 3)

In [16]:
climate_data.dtype

dtype('int32')

In [17]:
weights.dtype

dtype('float64')

In [18]:
np.matmul(climate_data , weights)

array([98.1, 98.1, 98.1, 98.1, 98.1])

In [19]:
#same as matrix multiplication
climate_data @ weights

array([98.1, 98.1, 98.1, 98.1, 98.1])

## Working with CSV Data Files

In [20]:
climate_data = np.genfromtxt('C:\\Users\\AAYUSH SOOD\\Desktop\\Coding\\Data Analysis\\climate.txt', delimiter=',', skip_header=1)

In [21]:
climate_data

array([[ 36.4,  31.2,   2. ],
       [ 27.4,  65.1,   5.5],
       [ 35.7,  74.9,   3.3],
       [ -0.2,  22.7,   8.8],
       [ 20.6,  71.3,   4.1],
       [ -4.3,  38.8,   1.1],
       [ -6.3,  98.9,   1.1],
       [ 26.6,  21.8,   5. ],
       [ 22.3,  28.9,   2.2],
       [ -8.9,  25.6,   3.7],
       [ 28.9,  40.5,   1.1],
       [ 28.2,  99.2,  17.2],
       [ 17.7,  81.5,   3.8],
       [ 32.6,  45.5,  10. ],
       [  6.5,  89.3,   3.6],
       [ -3. ,  45. ,   1.2],
       [ 12.7,  56.5,   6.6],
       [ 28.7,  69.2,   4.1],
       [ 13.3,  53.1,   2.9],
       [ 33.2,  40.4,   3.1],
       [ 12.8,  95. ,   2.3],
       [ -6.1,  41.8,  36.3],
       [  8.3,  23.5,   4.1],
       [ 34.7,  92.6,   4.7],
       [ 28.8,  58.5,   3.2],
       [ -7.5,  40.7,   4.3],
       [ 20.1,  78.8,   3.9],
       [ -6.4,  85.4,   2.4],
       [ 31.1,  22.2,   0.6],
       [ 30.2,  62.5,   4.9],
       [ -5. ,  22.4,  15.8],
       [ 18.9,  83.4,   0.4],
       [ 37.7,  24. ,   2.5],
       [ 2

In [22]:
climate_data.shape

(100, 3)

In [23]:
weights = np.array([0.8 , 0.3 , 0.5])

In [24]:
yields = np.matmul(climate_data , weights)

In [25]:
yields

array([39.48, 44.2 , 52.68, 11.05, 39.92,  8.75, 25.18, 30.32, 27.61,
        2.41, 35.82, 60.92, 40.51, 44.73, 33.79, 11.7 , 30.41, 45.77,
       28.02, 40.23, 39.89, 25.81, 15.74, 57.89, 42.19,  8.36, 41.67,
       21.7 , 31.84, 45.36, 10.62, 40.34, 38.61, 40.08, 40.38,  9.45,
       29.11, 28.09, 49.43, 46.34, 31.7 , 37.59, 42.56, 28.74, 59.35,
       21.08, 62.75, 46.91, 11.17, 50.65,  1.48, 51.36, 63.2 , 31.1 ,
       45.5 , 44.27, 36.69, 33.17,  7.39, 28.45, 13.15, 31.41, 54.16,
       55.83, 33.16, 58.68, 28.61, 32.46, 20.96,  7.84, 14.66, 47.25,
       26.88, 31.26, 35.7 , 42.67, 42.19, 29.5 , 38.35, 28.08, 23.2 ,
       33.65, 35.75, 21.09, 42.67, 53.39, 29.05, 32.39, 45.23, 26.61,
        9.6 , 33.21, 16.95, 30.8 , 28.02, 43.28, 41.22, 49.53, 13.22,
       37.01])

In [26]:
yields.shape

(100,)

In [27]:
climate_results = np.concatenate((climate_data , yields.reshape(100 ,1)) , axis = 1)

In [28]:
climate_results

array([[ 36.4 ,  31.2 ,   2.  ,  39.48],
       [ 27.4 ,  65.1 ,   5.5 ,  44.2 ],
       [ 35.7 ,  74.9 ,   3.3 ,  52.68],
       [ -0.2 ,  22.7 ,   8.8 ,  11.05],
       [ 20.6 ,  71.3 ,   4.1 ,  39.92],
       [ -4.3 ,  38.8 ,   1.1 ,   8.75],
       [ -6.3 ,  98.9 ,   1.1 ,  25.18],
       [ 26.6 ,  21.8 ,   5.  ,  30.32],
       [ 22.3 ,  28.9 ,   2.2 ,  27.61],
       [ -8.9 ,  25.6 ,   3.7 ,   2.41],
       [ 28.9 ,  40.5 ,   1.1 ,  35.82],
       [ 28.2 ,  99.2 ,  17.2 ,  60.92],
       [ 17.7 ,  81.5 ,   3.8 ,  40.51],
       [ 32.6 ,  45.5 ,  10.  ,  44.73],
       [  6.5 ,  89.3 ,   3.6 ,  33.79],
       [ -3.  ,  45.  ,   1.2 ,  11.7 ],
       [ 12.7 ,  56.5 ,   6.6 ,  30.41],
       [ 28.7 ,  69.2 ,   4.1 ,  45.77],
       [ 13.3 ,  53.1 ,   2.9 ,  28.02],
       [ 33.2 ,  40.4 ,   3.1 ,  40.23],
       [ 12.8 ,  95.  ,   2.3 ,  39.89],
       [ -6.1 ,  41.8 ,  36.3 ,  25.81],
       [  8.3 ,  23.5 ,   4.1 ,  15.74],
       [ 34.7 ,  92.6 ,   4.7 ,  57.89],
       [ 28.8 , 

In [29]:
np.savetxt?

Signature:      
np.savetxt(
    fname,
    X,
    fmt='%.18e',
    delimiter=' ',
    newline='\n',
    header='',
    footer='',
    comments='# ',
    encoding=None,
)
Call signature:  np.savetxt(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function savetxt at 0x00000202BFB26C00>
File:            c:\users\aayush sood\anaconda3\lib\site-packages\numpy\lib\npyio.py
Docstring:      
Save an array to a text file.

Parameters
----------
fname : filename or file handle
    If the filename ends in ``.gz``, the file is automatically saved in
    compressed gzip format.  `loadtxt` understands gzipped files
    transparently.
X : 1D or 2D array_like
    Data to be saved to a text file.
fmt : str or sequence of strs, optional
    A single format (%10.5f), a sequence of formats, or a
    multi-format string, e.g. 'Iteration %d -- %10.5f', in which
    case `delimiter` is ignored. For complex `X`, the legal options
    for `fmt` are:

    * a single specifier, `fm

In [30]:
np.savetxt('climate_results.txt', climate_results , fmt='%.2f' , header="temperature,rainfall,humidity,yield_of_apples" , delimiter = ',' , comments = '')

## Arithmetic Operations and Broadcasting

In [31]:
arr1 = np.array([[1,2,3] , [2,5,23] , [123,213,21]])
arr2 = np.array([[1,2,3] , [2,5,23] , [123,213,21]])

In [32]:
arr1 + arr2

array([[  2,   4,   6],
       [  4,  10,  46],
       [246, 426,  42]])

In [33]:
arr1 + 3

array([[  4,   5,   6],
       [  5,   8,  26],
       [126, 216,  24]])

In [34]:
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
arr1 / 2

array([[  0.5,   1. ,   1.5],
       [  1. ,   2.5,  11.5],
       [ 61.5, 106.5,  10.5]])

In [36]:
arr1 * arr2

array([[    1,     4,     9],
       [    4,    25,   529],
       [15129, 45369,   441]])

In [37]:
arr1 % 6

array([[1, 2, 3],
       [2, 5, 5],
       [3, 3, 3]], dtype=int32)

#### Broadcasting: Replicating of smaller array to make operations possible

In [38]:
arr1 = np.array([[1,2,3,4] , [1,2,3,4] , [1,2,3,4]])
arr2 = np.array([1,2,3,4])

In [39]:
arr1.shape

(3, 4)

In [40]:
arr2.shape

(4,)

In [41]:
arr1 + arr2

array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

## Comparison Operations

In [42]:
arr1 = np.array([[1,2,3] , [1,2,3]])
arr2 = np.array([[1,2,3] , [1,2,3]])

In [43]:
arr1 == arr2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [44]:
arr1 < arr2

array([[False, False, False],
       [False, False, False]])

In [45]:
arr1 > arr2

array([[False, False, False],
       [False, False, False]])

## Array Indexing and Slicing

In [46]:
arr1 = np.array([[[1 , 2 , 3 , 4] , [1 , 2 , 3 , 4] ,[1 , 2 , 3 , 4] ,] , [[1 , 2 , 3 , 4] ,[1 , 2 , 3 , 4] ,[1 , 2 , 3 , 4] ,] , [[1 , 2 , 3 , 4] ,[1 , 2 , 3 , 4] ,[1 , 2 , 3 , 4] ,]])

In [47]:
arr1.shape

(3, 3, 4)

In [48]:
arr1[1,2,3] # single element

4

In [49]:
arr1[1: , 0:1 , 2:]

array([[[3, 4]],

       [[3, 4]]])

In [50]:
arr1[1: , 1 , 3]

array([4, 4])

## Other ways of creating numpy arrays

In [51]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.random.rand(2,3)

array([[0.91745387, 0.68362065, 0.44740537],
       [0.67486037, 0.73353917, 0.15186164]])

In [55]:
np.full((2,3) , 20)

array([[20, 20, 20],
       [20, 20, 20]])

In [56]:
np.arange(10,90,3) # from 10 to 90 with a diff of 3

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [57]:
np.linspace(10,90,30) # 30 divisions from 10 to 90

array([10.        , 12.75862069, 15.51724138, 18.27586207, 21.03448276,
       23.79310345, 26.55172414, 29.31034483, 32.06896552, 34.82758621,
       37.5862069 , 40.34482759, 43.10344828, 45.86206897, 48.62068966,
       51.37931034, 54.13793103, 56.89655172, 59.65517241, 62.4137931 ,
       65.17241379, 67.93103448, 70.68965517, 73.44827586, 76.20689655,
       78.96551724, 81.72413793, 84.48275862, 87.24137931, 90.        ])